version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
#   localstack_postgres:
#     container_name: localstack_postgres_container
#     image: postgres
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER:-postgres}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
#       PGDATA: /data/postgres
#     volumes:
#        - postgres:/data/postgres
#        - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
#        # Any .sql, .sh, .sql.gz files in the /docker-entrypoint-initdb.d directory will be automatically executed in alphabetical order when the container starts up for the first time.
#     ports:
#       - "5432:5432"
#     networks:
#       - postgres
#     restart: unless-stopped

# networks:
#   postgres:  # Define the network here
#     driver: bridge

# volumes:
#   postgres:
  